---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ejbca-issuer.keyfactor.com
  resources:
  - clusterissuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ejbca-issuer.keyfactor.com
  resources:
  - clusterissuers/finalizers
  verbs:
  - update
- apiGroups:
  - ejbca-issuer.keyfactor.com
  resources:
  - clusterissuers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ejbca-issuer.keyfactor.com
  resources:
  - issuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ejbca-issuer.keyfactor.com
  resources:
  - issuers/finalizers
  verbs:
  - update
- apiGroups:
  - ejbca-issuer.keyfactor.com
  resources:
  - issuers/status
  verbs:
  - get
  - patch
  - update
